version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  groups:
    gomod-dependencies:
      patterns:
      - x
- package-ecosystem: gomod
  directory: /konnectivity-client
  schedule:
    interval: weekly
  groups:
    gomod-dependencies:
      patterns:
      - x
